- apiVersion: kafka.strimzi.io/v1
  kind: KafkaNodePool
  metadata:
    name: kafka
    namespace: "{{ ENV.COMMON.NAMESPACE }}"
    labels:
      strimzi.io/cluster: backend-eventstore
  spec:
    replicas: {{ ENV.BACKEND_EVENTSTORE.REPLICAS}}
    roles:
      - controller
      - broker
    resources:
      requests:
        cpu: "100m"
        memory: "{{ ENV.BACKEND_EVENTSTORE.LIMIT_MEMORY }}Mi"
      limits:
        cpu: "{{ ENV.BACKEND_EVENTSTORE.LIMIT_CPU }}"
        memory: "{{ ENV.BACKEND_EVENTSTORE.LIMIT_MEMORY }}Mi"
    jvmOptions:
      -Xms: "{{ (ENV.BACKEND_EVENTSTORE.LIMIT_MEMORY | int * 0.3) | int}}m" # Minimum heap size
      -Xmx: "{{ (ENV.BACKEND_EVENTSTORE.LIMIT_MEMORY | int * 0.3) | int}}m" # Maximum heap size
#      -Xms: 128m 
#      -Xmx: 512m
    storage:
      type: jbod
      volumes:
        - id: 0
          type: persistent-claim
          size: "{{ ENV.BACKEND_EVENTSTORE.STORAGE_SIZE }}"
          class: "{{ ENV.COMMON.K8S.STORAGE_CLASS_FILE}}"
          deleteClaim: true
          kraftMetadata: shared

- kind: Kafka
  apiVersion: kafka.strimzi.io/v1
  metadata:
    name: backend-eventstore
    namespace: "{{ ENV.COMMON.NAMESPACE }}"
  spec:
    kafka:
      version: "4.3.0"
      metadataVersion: "4.3"
      listeners:
        - name: plain
          port: 9092
          type: internal
          tls: false
        - name: tls
          port: 9093
          type: internal
          tls: true

      config:
        offsets.topic.replication.factor: {{ ENV.BACKEND_EVENTSTORE.REPLICAS}}
        transaction.state.log.replication.factor: {{ ENV.BACKEND_EVENTSTORE.REPLICAS}}
        transaction.state.log.min.isr: {{ ENV.BACKEND_EVENTSTORE.REPLICAS}}
        default.replication.factor: {{ ENV.BACKEND_EVENTSTORE.REPLICAS}}
        min.insync.replicas: {{ ENV.BACKEND_EVENTSTORE.REPLICAS}}
#    entityOperator:
#      topicOperator: {}
#      userOperator: {}