- apiVersion: kafka.strimzi.io/v1beta2
  kind: KafkaNodePool
  metadata:
    name: dual-role
    namespace: "{{ ENV.COMMON.NAMESPACE }}"
    labels:
      strimzi.io/cluster: backend-eventstore
  spec:
    replicas: {{ ENV.BACKEND_EVENTSTORE.REPLICAS}}
    roles:
      - controller
      - broker
    storage:
      type: jbod
      volumes:
        - id: 0
          type: persistent-claim
          size: 2Gi
          class: "{{ ENV.COMMON.K8S.STORAGE_CLASS_FILE}}"
          deleteClaim: true
          kraftMetadata: shared

- kind: Kafka
  apiVersion: kafka.strimzi.io/v1beta2
  metadata:
    name: backend-eventstore
    namespace: "{{ ENV.COMMON.NAMESPACE }}"
  spec:
    kafka:
      version: 4.1.0
      metadataVersion: 4.1-IV1
      listeners:
        - name: plain
          port: 9092
          type: internal
          tls: false
        - name: tls
          port: 9093
          type: internal
          tls: true
      config:
        offsets.topic.replication.factor: {{ ENV.BACKEND_EVENTSTORE.REPLICAS}}
        transaction.state.log.replication.factor: {{ ENV.BACKEND_EVENTSTORE.REPLICAS}}
        transaction.state.log.min.isr: {{ ENV.BACKEND_EVENTSTORE.REPLICAS}}
        default.replication.factor: {{ ENV.BACKEND_EVENTSTORE.REPLICAS}}
        min.insync.replicas: {{ ENV.BACKEND_EVENTSTORE.REPLICAS}}
    entityOperator:
      topicOperator: {}
      userOperator: {}