---
- name: Install service-eventactivity
  gather_facts: false
  hosts: localhost
  vars_files:
    - ../../../install/openshift/vars_secrets.yml
    - ../../../install/openshift/vars_common.yml
    - ../../../install/openshift/vars_env_{{ STAGE }}.yml
  tasks:
    - name: "Combine env facts"
      tags: always
      set_fact:
        ENV: "{{ common | combine( specific, recursive=True) }}"

    - name: Skip deployment if not needed
      meta: end_play
      when: not ENV.SERVICE_EVENTACTIVITY.DEPLOY

    - name: Create kafka topic using operator
      tags: kafka
      when: ENV.BACKEND_EVENTSTORE.KAFKA.USE
      k8s:
        state: present
        wait: true
        definition:
          kind: KafkaTopic
          apiVersion: kafka.strimzi.io/v1beta1
          metadata:
            name: opendj.event.activity
            labels:
              strimzi.io/cluster: backend-eventstore
            namespace: "{{ENV.COMMON.NAMESPACE|mandatory}}"
          spec:
            partitions: 1
            replicas: 1
            config:
              retention.ms: 604800000
              segment.bytes: 1073741824

    - name: Create definitions for image build 
      when: ENV.COMMON.CONTAINER_IMAGE_BUILD
      k8s:
        state: present
        wait: true
        validate:
            fail_on_error: no
            strict: no
        definition: "{{ (lookup('template', 'definitionsForImageBuild.yml') | from_yaml_all | list)[0] }}"

    - name: Create definitions for external image
      when: ENV.COMMON.CONTAINER.IMAGE_FROM_EXTERNAL_REGISTRY
      k8s:
        state: present
        wait: true
        validate:
            fail_on_error: no
            strict: no
        definition: "{{ (lookup('template', 'definitionsForExternalImage.yml') | from_yaml_all | list)[0] }}"

    - name: Create definitions for deployment
      k8s:
        state: present
        wait: true
        validate:
            fail_on_error: no
            strict: no
        definition: "{{ (lookup('template', 'definitionsForDeployment.yml') | from_yaml_all | list)[0] }}"
    - name: Create Route with Let's Encrypt Certs
      when: ENV.FRONTEND_WEB.USE_ACME_CERTS|bool
      k8s:
        state: present
        wait: true
        definition:
          kind: Route
          apiVersion: route.openshift.io/v1
          metadata:
            annotations:
              haproxy.router.openshift.io/balance: "roundrobin"
              kubernetes.io/tls-acme: "true"
            labels:
              app: service-eventactivity
            name: service-eventactivity
            namespace: "{{ENV.COMMON.NAMESPACE|mandatory}}"
          spec:
            host: "{{ENV.COMMON.DNS_BASENAME|mandatory}}"
            path: /api/service-eventactivity
            port:
              targetPort: web
              tls:
                insecureEdgeTerminationPolicy: "{{ENV.FRONTEND_WEB.INSECURE_EDGE_TERMINATION}}"
                termination: "edge"
            to:
              kind: Service
              name: service-eventactivity
              weight: 100
            wildcardPolicy: None
            
    - name: Create Route with custom certs
      when: not ENV.FRONTEND_WEB.USE_ACME_CERTS|bool
      k8s:
        state: present
        wait: true
        definition:
          kind: Route
          apiVersion: route.openshift.io/v1
          metadata:
            annotations:
              haproxy.router.openshift.io/balance: "roundrobin"
            labels:
              app: service-eventactivity
            name: service-eventactivity
            namespace: "{{ENV.COMMON.NAMESPACE|mandatory}}"
          spec:
            host: "{{ENV.COMMON.DNS_BASENAME|mandatory}}"
            path: /api/service-eventactivity
            port:
              targetPort: web
            tls:
              insecureEdgeTerminationPolicy: "{{ENV.FRONTEND_WEB.INSECURE_EDGE_TERMINATION}}"
              termination: "edge"
              certificate: "{{ENV.FRONTEND_WEB.TLS_CERT}}"
              key: "{{ENV.FRONTEND_WEB.TLS_KEY}}"
            to:
              kind: Service
              name: service-eventactivity
              weight: 100
            wildcardPolicy: None


